/* eslint-disable max-len */
export const MODULE_DECENTRALIZED_CONFIG = [
    { isStaff: true, name: 'Quản lý phòng ban', module: 'SFF_DEPARTMENT', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Quản lý nhân viên', module: 'SFF_EMPLOYEE', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Quản lý nhà đầu tư', module: 'SFF_INVESTOR', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Quản lý bên huy động vốn', module: 'SFF_BORROWER', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Cấu hình cảnh báo', module: 'SFF_CONFIGURING_ALERTS', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Cấu hình email', module: 'SFF_EMAIL_CONFIGURATION', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Xử lý giao dịch nạp tiền', module: 'SFF_RECHARGE_TRANSACTION', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Xử lý giao dịch giải ngân', module: 'SFF_DISBURSEMENT_TRANSACTION', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Thanh toán khoản vay bên huy động vốn', module: 'SFF_REFUND_TRANSACTION', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Quản lý giao dịch', module: 'SFF_MANAGE_TRANSACTION_FEES', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Quản lý thuế TNCN', module: 'SFF_PERSONAL_INCOME_TAX', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Xử lý giao dịch rút tiền', module: 'FSS_WITHDRAW_CASH_TRANSACTION', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Thanh toán hoa hồng', module: 'SFF_COMMISSION_PAYMENT', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Xử lý yêu cầu thanh toán hoa hồng', module: 'SFF_PROCESSING_COMMISSION', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Tiếp quỹ tiền mặt/tiền điện tử', module: 'SFF_CASH_CURRENCY_FUNDING', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Xử lý yêu cầu tiếp quỹ', module: 'SFF_PROCESSING_FUNDING', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Điều chuyển tiền ví', module: 'SFF_WALLET_MONEY_TRANSFER', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Xử lý yêu cầu điều chuyển tiền ví', module: 'SFF_TRANSFER_REQUESTS', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Rút tiền ví từ tài khoản HO', module: 'SFF_WITHDRAW_WALLET', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Xử lý yêu cầu rút tiền từ tài khoản HO', module: 'SFF_PROCESSING_WALLET', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Báo cáo thống kê', module: 'SFF_STATISTIC', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Hồ sơ đang xem xét', module: 'SFF_PROFILE_REVIEW', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Hồ sơ tiếp nhận', module: 'SFF_PROFILE_RECEIPT', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Hồ sơ đang xử lý', module: 'SFF_PROFILE_IN_PROGRESS', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Hồ sơ đã phê duyệt', module: 'SFF_PROFILE_APPROVED', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Hồ sơ bị từ chối', module: 'SFF_PROFILE_REJECTED', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Hồ sơ yêu cầu làm lại', module: 'SFF_PROFILE_REDO', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Hồ sơ bị huỷ', module: 'SFF_PROFILE_CANCELED', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Hồ sơ trình HĐ tín dụng', module: 'SFF_PROFILE_SUBMIT_CREDIT_CONTRACT', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Hồ sơ đã giải ngân', module: 'SFF_PROFILE_DISBURSED', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Hồ sơ chờ tất toán khoản vay', module: '', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Hồ sơ lưu trữ', module: 'SFF_PROFILE_STORE', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Phê duyệt YC thay đổi ID', module: 'SFF_CHANGE_ID', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Quản lý module', module: 'SFF_MODULE_MANAGEMENT', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Cấu hình thông tin tài khoản ngân hàng', module: 'SFF_CONFIGURE_BANK_ACCOUNT', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Cấu hình biểu mẫu', module: 'SFF_FORM_CONFIGURATION', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Tuỳ chỉnh sản phẩm huy động vốn', module: 'SFF_CUSTOM_CREDIT_PRODUCTS', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Quản lý tài khoản bảo đảm', module: 'SFF_SECURED_ASSET_MANAGEMENT', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Quản lý nợ quá hạn, nợ xấu', module: 'SFF_MANAGEMENT_DEBT', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    { isStaff: true, name: 'Theo dõi công nợ', module: 'SFF_DEBT_TRACKING', isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false },
    // { name: '', module: '' , isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false  },
    // { name: '', module: '' , isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false  },
    // { name: '', module: '' , isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false  },
    // { name: '', module: '' , isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false  },
    // { name: '', module: '' , isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false  },
    // { name: '', module: '' , isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false  },
    // { name: '', module: '' , isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false  },
    // { name: '', module: '' , isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false  },
    // { name: '', module: '' , isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false  },
    // { name: '', module: '' , isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false  },
    // { name: '', module: '' , isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false  },
    // { name: '', module: '' , isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false  },
    // { name: '', module: '' , isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false  },
    // { name: '', module: '' , isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false  },
    // { name: '', module: '' , isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false  },
    // { name: '', module: '' , isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false  },
    // { name: '', module: '' , isSelect: false, isInsert: false, isUpdate: false, isDelete: false, isExport: false, isAcceptance: false  },
];
